name: angular-todo.yml

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node ${{ env.NODE_VERSION }}
        env:
          NODE_VERSION: '14.x'
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: Publish build artifacts
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist
      - name: Publish code coverage results
        uses: actions/upload-artifact@v1
        with:
          name: coverage
          path: coverage
